package apperror

import "errors"

var (
	ErrInvalidEmail         = errors.New("Invalid Email Format")
	ErrInvalidPassword      = errors.New("Invalid Password Format min 8 characters")
	ErrUserNotFound         = errors.New("User not found")
	ErrInternalServer       = errors.New("Internal server error")
	ErrEmailRegistered      = errors.New("Email already registered")
	ErrOTPInvalid           = errors.New("Invalid otp code")
	ErrOTPExpired           = errors.New("Otp expired or not found")
	ErrInvalidCredentials   = errors.New("Invalid Email or Password")
	ErrCredentialsRequired  = errors.New("Email and Password are required")
	MovieNotFound           = errors.New("Movie not found")
	MovieGenresNotFound     = errors.New("Genre not found")
	MovieCastsNotFound      = errors.New("Cast not found")
	InvalidSeatsInput       = errors.New("Seats is required")
	InvalidQuantity         = errors.New("Quantity is not the same as the number of seats ordered")
	SeatsUnavailable        = errors.New("Seat already taken")
	ErrAccountNotActivated  = errors.New("ACCOUNT_NOT_ACTIVATED")
	ErrAccountAlreadyActive = errors.New("Account is already activated")
	ErrResetTokenExpired    = errors.New("Unauthorized or session expired, please verify OTP again")
	BookingNotFound         = errors.New("Booking data not found")
	UserIstMatch            = errors.New("User is not the same as the User who made the booking")
	ForbiddenBooking        = errors.New("Forbidden, booking does not belong to User")
	TicketNotFound          = errors.New("Forbidden, ticket does not belong to User")
	TicketAlreadyPaid       = errors.New("Forbidden, ticket have been paid")
	ErrMissingAuthHeader    = errors.New("Authorization header is required")
	ErrTokenRevoked         = errors.New("Token has been revoked or logged out")
)
